# Site settings
title: asxzy Blog
email: asxzy@asxzy.net
description: > # this means to ignore newlines until "baseurl:"
My Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "asxzy.net" # the base hostname & protocol for your site
twitter_username: asxzy
github_username:  asxzy

# Build settings
markdown: kramdown

# pagination
paginate: 10

